import Link from "next/link";

import { Breadcrumbs } from "@/components/content/breadcrumbs";
import { GeneratorCta } from "@/components/content/generator-cta";
import type { ShiftScheduleGuide } from "@/content/content-types";
import { shiftLabel, shiftScheduleGuides } from "@/content/shift-schedules";

const dateFormatter = new Intl.DateTimeFormat("en", {
  weekday: "short",
  year: "numeric",
  month: "short",
  day: "numeric",
  timeZone: "UTC",
});

function formatDate(date: string): string {
  return dateFormatter.format(new Date(`${date}T00:00:00Z`));
}

export function PatternGuide({ guide }: { guide: ShiftScheduleGuide }) {
  const related = shiftScheduleGuides[guide.relatedPresetId];

  return (
    <main id="main-content">
      <article className="mx-auto w-full max-w-4xl px-5 py-10 sm:px-8 sm:py-14">
        <Breadcrumbs
          items={[
            { label: "Home", path: "/" },
            { label: "Shift schedules", path: "/shift-schedules" },
            { label: guide.label, path: guide.seo.path },
          ]}
        />

        <header className="mt-8 max-w-3xl">
          <p className="text-primary text-sm font-semibold tracking-wide uppercase">
            Shift pattern guide
          </p>
          <h1 className="mt-3 text-4xl font-bold tracking-[-0.03em] text-balance sm:text-5xl">
            {guide.h1}
          </h1>
          <p className="text-muted-foreground mt-5 text-lg leading-8">
            {guide.definition}
          </p>
        </header>

        <div className="mt-12 space-y-12">
          <section aria-labelledby="cycle-heading">
            <h2
              id="cycle-heading"
              className="text-2xl font-bold tracking-tight"
            >
              The exact cycle supported here
            </h2>
            <p className="text-muted-foreground mt-3 leading-7">
              This cycle has {guide.cycleLength} positions:{" "}
              {guide.workPositions} working and {guide.offPositions} off. With
              Day selected, the positions are:
            </p>
            <ol
              className={`mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4 ${guide.cycleLength === 8 ? "md:grid-cols-4" : "md:grid-cols-7"}`}
            >
              {guide.cycle.map((shift, index) => (
                <li
                  className="border-border bg-card rounded-lg border p-3 text-center"
                  key={`${shift}-${index}`}
                >
                  <span className="text-muted-foreground block text-xs">
                    Position {index + 1}
                  </span>
                  <span className="mt-1 block font-semibold">
                    {shiftLabel(shift)}
                  </span>
                </li>
              ))}
            </ol>
          </section>

          <section aria-labelledby="example-heading">
            <h2
              id="example-heading"
              className="text-2xl font-bold tracking-tight"
            >
              One complete cycle from January 5, 2026
            </h2>
            <p className="text-muted-foreground mt-3 leading-7">
              This fixed example starts on {guide.exampleStart} with Day
              selected. It is generated by the same schedule engine as the
              calendar tool.
            </p>
            <div className="border-border mt-5 overflow-x-auto rounded-xl border">
              <table className="w-full min-w-[32rem] border-collapse text-left text-sm">
                <caption className="sr-only">
                  {guide.label} example beginning January 5, 2026
                </caption>
                <thead className="bg-muted/70">
                  <tr>
                    <th className="px-4 py-3 font-semibold" scope="col">
                      Date
                    </th>
                    <th className="px-4 py-3 font-semibold" scope="col">
                      Cycle position
                    </th>
                    <th className="px-4 py-3 font-semibold" scope="col">
                      Status
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {guide.example.map((row) => (
                    <tr className="border-border border-t" key={row.date}>
                      <td className="px-4 py-3">
                        <time dateTime={row.date}>{formatDate(row.date)}</time>
                      </td>
                      <td className="px-4 py-3">{row.cyclePosition}</td>
                      <td className="px-4 py-3 font-medium">
                        {shiftLabel(row.shift)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section aria-labelledby="anchor-heading">
            <h2
              id="anchor-heading"
              className="text-2xl font-bold tracking-tight"
            >
              Start date and Day/Night choice
            </h2>
            <p className="text-muted-foreground mt-3 leading-7">
              {guide.anchorExplanation}
            </p>
            <p className="text-muted-foreground mt-3 leading-7">
              {guide.shiftExplanation}
            </p>
          </section>

          {guide.terminologyNote ? (
            <section aria-labelledby="terms-heading">
              <h2
                id="terms-heading"
                className="text-2xl font-bold tracking-tight"
              >
                A note about the name
              </h2>
              <p className="text-muted-foreground mt-3 leading-7">
                {guide.terminologyNote}
              </p>
            </section>
          ) : null}

          <section aria-labelledby="considerations-heading">
            <h2
              id="considerations-heading"
              className="text-2xl font-bold tracking-tight"
            >
              Practical considerations
            </h2>
            <div className="mt-5 grid gap-6 md:grid-cols-2">
              <div>
                <h3 className="text-lg font-bold">Potential advantages</h3>
                <ul className="text-muted-foreground mt-3 list-disc space-y-2 pl-5 leading-7">
                  {guide.advantages.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-bold">Tradeoffs to check</h3>
                <ul className="text-muted-foreground mt-3 list-disc space-y-2 pl-5 leading-7">
                  {guide.tradeoffs.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              </div>
            </div>
            <h3 className="mt-7 text-lg font-bold">
              Who may compare this pattern
            </h3>
            <p className="text-muted-foreground mt-3 leading-7">
              {guide.audience}
            </p>
          </section>

          <section aria-labelledby="how-heading">
            <h2 id="how-heading" className="text-2xl font-bold tracking-tight">
              How to generate your calendar
            </h2>
            <ol className="text-muted-foreground mt-4 list-decimal space-y-2 pl-5 leading-7">
              <li>Open the generator and choose the {guide.label} preset.</li>
              <li>
                Enter the confirmed first working date for cycle position 1.
              </li>
              <li>Select fixed Day or Night, then generate the schedule.</li>
              <li>
                Check several known dates before printing, sharing, or
                exporting.
              </li>
            </ol>
          </section>

          <GeneratorCta label={`Create your ${guide.shortLabel} calendar`} />

          <section aria-labelledby="faq-heading">
            <h2 id="faq-heading" className="text-2xl font-bold tracking-tight">
              Frequently asked questions
            </h2>
            <div className="mt-5 space-y-6">
              {guide.faqs.map((faq) => (
                <section key={faq.question}>
                  <h3 className="text-lg font-bold">{faq.question}</h3>
                  <p className="text-muted-foreground mt-2 leading-7">
                    {faq.answer}
                  </p>
                </section>
              ))}
            </div>
          </section>

          <aside className="border-border bg-muted/40 rounded-xl border p-5">
            <h2 className="text-lg font-bold">
              Check the result against your rota
            </h2>
            <p className="text-muted-foreground mt-2 leading-7">
              {guide.accuracyNote}
            </p>
          </aside>

          <nav
            aria-label="Related pages"
            className="border-border border-t pt-8"
          >
            <h2 className="text-lg font-bold">Related pages</h2>
            <ul className="mt-3 flex flex-wrap gap-x-6 gap-y-3">
              <li>
                <Link
                  className="text-primary underline-offset-4 hover:underline"
                  href="/shift-schedules"
                >
                  Compare shift schedule patterns
                </Link>
              </li>
              <li>
                <Link
                  className="text-primary underline-offset-4 hover:underline"
                  href={related.seo.path}
                >
                  Read the {related.label} guide
                </Link>
              </li>
              <li>
                <Link
                  className="text-primary underline-offset-4 hover:underline"
                  href="/about"
                >
                  About the calculation method
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </article>
    </main>
  );
}
